apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/belitradas/environment-songrogue-dev.git
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackName: classic-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-classic.git
    defaultScheduler:
      kind: ""
      name: ""
    envOrganisation: belitradas
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: belitre-ci-bot
    promotionEngine: Prow
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://coolcluster-lts-92c8f49e-8920-458e-8671-5e0ea4a15f0b
      classifier: default
    - bucketUrl: gs://coolcluster-lts-92c8f49e-8920-458e-8671-5e0ea4a15f0b
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
