# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

PipelineSecrets:

  # lets enable GCR docker builds
  DockerConfig: |-
    {
        "credHelpers": {
            "gcr.io": "gcr",
            "us.gcr.io": "gcr",
            "eu.gcr.io": "gcr",
            "asia.gcr.io": "gcr",
            "staging-k8s.gcr.io": "gcr"
        }
    }
pipelinecontroller:
  enabled: true
docker-registry:
  enabled: false
nexus:
  enabled: false
nexusServiceLink:
  enabled: false
chartmuseum:
  enabled: false
chartmuseumServiceLink:
  enabled: false
monocular:
  enabled: false
auth:
  git:
    username: belitre-ci-bot
build:
  enabled: false
buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
tillerNamespace: ""
